FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port de Next.js
EXPOSE 3000

# Lancer le serveur de développement
CMD ["npm", "run", "dev"]
